package br.com.livraria.visao;

import br.com.livraria.controle.LivroDaoArquivo;
import br.com.livraria.modelo.Livro;
import java.io.IOException;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

public class CadastroLivro extends javax.swing.JFrame {
     
    private LivroDaoArquivo dao;
    
    public CadastroLivro() {
        try {
            dao = new LivroDaoArquivo();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo!",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJPanelImagem1 = new componentes.UJPanelImagem();
        LabelLivro = new javax.swing.JLabel();
        LabelCodigo = new javax.swing.JLabel();
        TextFieldCodigo = new javax.swing.JTextField();
        ButtonPesquisar = new javax.swing.JButton();
        LabelTitulo = new javax.swing.JLabel();
        TextFieldTitulo = new javax.swing.JTextField();
        LabelAutor = new javax.swing.JLabel();
        TextFieldAutor = new javax.swing.JTextField();
        LabelGenero = new javax.swing.JLabel();
        ComboBoxGenero = new javax.swing.JComboBox<>();
        LabelAno = new javax.swing.JLabel();
        LabelPreco = new javax.swing.JLabel();
        ButtonVoltar = new javax.swing.JButton();
        ButtonSalvar = new javax.swing.JButton();
        ButtonAtualizar = new javax.swing.JButton();
        ButtonDeletar = new javax.swing.JButton();
        AnoEdicao = new javax.swing.JTextField();
        Preco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\JOCERLANIA\\Documents\\Projetos\\Livraria\\src\\br\\com\\livraria\\imagens\\tela2.png"));

        LabelLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelLivro.setText("Cadastro de Livro");

        LabelCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCodigo.setText("Código de Barra");

        TextFieldCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ButtonPesquisar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/livraria/imagens/iconePesquisa.png"))); // NOI18N
        ButtonPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisarActionPerformed(evt);
            }
        });

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTitulo.setText("Título");

        TextFieldTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelAutor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelAutor.setText("Autor");

        TextFieldAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelGenero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelGenero.setText("Gênero");

        ComboBoxGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Autoajuda", "Aventura", "Contos/Crônicas", "Poesia", "Policial", "Romance", "Terro/Suspense" }));

        LabelAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelAno.setText("Ano de Edição");

        LabelPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelPreco.setText("Preço");

        ButtonVoltar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/livraria/imagens/iconeVoltar.png"))); // NOI18N
        ButtonVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonSalvar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonSalvar.setText("Salvar");
        ButtonSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonAtualizar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonAtualizar.setText("Atualizar");
        ButtonAtualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtualizarActionPerformed(evt);
            }
        });

        ButtonDeletar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonDeletar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonDeletar.setText("Deletar");
        ButtonDeletar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeletarActionPerformed(evt);
            }
        });

        AnoEdicao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Preco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addComponent(LabelTitulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldTitulo))
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addComponent(LabelCodigo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(ButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addComponent(LabelGenero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ComboBoxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addComponent(LabelAutor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelAno)
                                        .addComponent(LabelPreco))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AnoEdicao)
                                        .addComponent(Preco))))))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ButtonVoltar)
                        .addGap(76, 76, 76)
                        .addComponent(LabelLivro)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelLivro)
                    .addComponent(ButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCodigo)
                    .addComponent(TextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTitulo)
                    .addComponent(TextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAutor)
                    .addComponent(TextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGenero)
                    .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAno)
                    .addComponent(AnoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPreco)
                    .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
       String ano = AnoEdicao.getText();
       int anoEdicao = parseInt(ano);
       String valor = Preco.getText();
       float preco = parseFloat(valor);
       String genero = (String) ComboBoxGenero.getSelectedItem();
       
       Livro l = new Livro(TextFieldCodigo.getText(),TextFieldTitulo.getText(),TextFieldAutor.getText(), genero, anoEdicao, preco);
            
        try{
            if(dao.salvar(l)){
                JOptionPane.showMessageDialog(null,"Livro cadastrado com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Falha ao casdastrar livro!",
                        "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IOException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisarActionPerformed
       String ano = AnoEdicao.getText();
       int anoEdicao = parseInt(ano);
       String valor = Preco.getText();
       float preco = parseInt(valor);
       
       
       Livro l = null;
            
        try{
            l = dao.buscar(TextFieldCodigo.getText());
        }catch(IOException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
        if(l == null){
            JOptionPane.showMessageDialog(null,"Livro não encontrado",
                    "Mensagem de erro", JOptionPane.INFORMATION_MESSAGE);
        }else{
            TextFieldAutor.setText(l.getAutor());
            ComboBoxGenero.setSelectedItem(l.getGenero());
           // AnoEdicao.setText(l.getAnoEdicao());
           // Preco.setText( l.getPreco());
            
            
        }
    }//GEN-LAST:event_ButtonPesquisarActionPerformed

    private void ButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtualizarActionPerformed
        String ano = AnoEdicao.getText();
       int anoEdicao = parseInt(ano);
       String valor = Preco.getText();
       float preco = parseFloat(valor);
       String genero = (String) ComboBoxGenero.getSelectedItem();
        
       Livro l = new Livro(TextFieldCodigo.getText(),TextFieldTitulo.getText(),TextFieldAutor.getText(), genero, anoEdicao, preco);
            
        try{
            if(dao.atualizar(l)){
                JOptionPane.showMessageDialog(null,"Livro atualizado com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Falha ao atualizar livro",
                        "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IOException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonAtualizarActionPerformed

    private void ButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeletarActionPerformed
       String ano = AnoEdicao.getText();
       int anoEdicao = parseInt(ano);
       String valor = Preco.getText();
       float preco = parseFloat(valor);
       String genero = (String) ComboBoxGenero.getSelectedItem();
        
       Livro l = new Livro(TextFieldCodigo.getText(),TextFieldTitulo.getText(),TextFieldAutor.getText(), genero, anoEdicao, preco);
            
        try{
            if(dao.deletar(l)){
                JOptionPane.showMessageDialog(null,"Livro excluido com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Falha ao excluir livro",
                        "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IOException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoEdicao;
    private javax.swing.JButton ButtonAtualizar;
    private javax.swing.JButton ButtonDeletar;
    private javax.swing.JButton ButtonPesquisar;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JComboBox<String> ComboBoxGenero;
    private javax.swing.JLabel LabelAno;
    private javax.swing.JLabel LabelAutor;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelGenero;
    private javax.swing.JLabel LabelLivro;
    private javax.swing.JLabel LabelPreco;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JTextField Preco;
    private javax.swing.JTextField TextFieldAutor;
    private javax.swing.JTextField TextFieldCodigo;
    private javax.swing.JTextField TextFieldTitulo;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables

        

}
