package br.com.livraria.visao;

import br.com.livraria.controle.FuncionarioDaoArquivo;
import br.com.livraria.modelo.Funcionario;
import java.io.IOException;
import static java.lang.Float.parseFloat;
import javax.swing.JOptionPane;

public class CadastroFuncionario extends javax.swing.JFrame {
    
    private FuncionarioDaoArquivo dao;
    
    public CadastroFuncionario() {
        try{
            dao = new FuncionarioDaoArquivo();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null,"Arquivo não encontrado",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uJPanelImagem1 = new componentes.UJPanelImagem();
        jLabel1 = new javax.swing.JLabel();
        LabelCpf = new javax.swing.JLabel();
        TextFieldCPF = new javax.swing.JFormattedTextField();
        LabelNome = new javax.swing.JLabel();
        TextFieldNome = new javax.swing.JTextField();
        LabelRG = new javax.swing.JLabel();
        TextFieldRG = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        TextFieldEmail = new javax.swing.JTextField();
        FormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        LabelTelefone = new javax.swing.JLabel();
        LabelCargo = new javax.swing.JLabel();
        ComboBoxCargo = new javax.swing.JComboBox<>();
        LabelSalario = new javax.swing.JLabel();
        TextFieldSalario = new javax.swing.JTextField();
        ButtonSalvar = new javax.swing.JButton();
        ButtonVoltar = new javax.swing.JButton();
        ButtonPesquisar = new javax.swing.JButton();
        ButtonAtualizar = new javax.swing.JButton();
        ButtonDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\JOCERLANIA\\Documents\\Projetos\\Livraria\\src\\br\\com\\livraria\\imagens\\tela2.png"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Funcionário");

        LabelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCpf.setText("CPF");

        try {
            TextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelNome.setText("Nome");

        TextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelRG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelRG.setText("RG");

        TextFieldRG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelEmail.setText("Email");

        TextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            FormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FormattedTextFieldTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelTelefone.setText("Telefone");

        LabelCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCargo.setText("Cargo");

        ComboBoxCargo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Gerente", "Vendedor", " " }));

        LabelSalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelSalario.setText("Salário");

        TextFieldSalario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ButtonSalvar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ButtonSalvar.setText("Salvar");
        ButtonSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonVoltar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/livraria/imagens/iconeVoltar.png"))); // NOI18N
        ButtonVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonPesquisar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/livraria/imagens/iconePesquisa.png"))); // NOI18N
        ButtonPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonAtualizar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ButtonAtualizar.setText("Atualizar");
        ButtonAtualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAtualizarActionPerformed(evt);
            }
        });

        ButtonDeletar.setBackground(new java.awt.Color(255, 102, 0));
        ButtonDeletar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ButtonDeletar.setText("Deletar");
        ButtonDeletar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ButtonSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(LabelTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCargo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSalario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ComboBoxCargo, 0, 147, Short.MAX_VALUE)
                                        .addComponent(FormattedTextFieldTelefone)
                                        .addComponent(TextFieldSalario)))
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFieldRG, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                        .addComponent(TextFieldEmail)
                                        .addComponent(TextFieldNome)
                                        .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                            .addComponent(TextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(ButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, uJPanelImagem1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(ButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(TextFieldCPF))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(FormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(426, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
       String valor = TextFieldSalario.getText();
       float salario = parseFloat(valor);
       String cargo = (String) ComboBoxCargo.getSelectedItem();
        
        Funcionario f = new Funcionario(TextFieldCPF.getText(),TextFieldNome.getText(),
                 TextFieldRG.getText(), TextFieldEmail.getText(), FormattedTextFieldTelefone.getText(),
                   cargo, salario);
            
        try{
            if(dao.salvar(f)){
                JOptionPane.showMessageDialog(null,"Funcionário cadastrado com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Falha ao casdastrar funcionário",
                        "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IOException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAtualizarActionPerformed
        String valor = TextFieldSalario.getText();
       float salario = parseFloat(valor);
       String cargo = (String) ComboBoxCargo.getSelectedItem();
        
        Funcionario f = new Funcionario(TextFieldCPF.getText(),TextFieldNome.getText(),
                 TextFieldRG.getText(), TextFieldEmail.getText(), FormattedTextFieldTelefone.getText(),
                   cargo, salario);
            
        try{
            if(dao.atualizar(f)){
                JOptionPane.showMessageDialog(null,"Funcionário cadastrado com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Falha ao casdastrar funcionário",
                        "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IOException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonAtualizarActionPerformed

    private void ButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeletarActionPerformed
        String valor = TextFieldSalario.getText();
       float salario = parseFloat(valor);
       String cargo = (String) ComboBoxCargo.getSelectedItem();
        
        Funcionario f = new Funcionario(TextFieldCPF.getText(),TextFieldNome.getText(),
                 TextFieldRG.getText(), TextFieldEmail.getText(), FormattedTextFieldTelefone.getText(),
                   cargo, salario);
            
        try{
            if(dao.deletar(f)){
                JOptionPane.showMessageDialog(null,"Funcionário cadastrado com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Falha ao cadastrar funcionário",
                        "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IOException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Falha na conexão com o arquivo",
                    "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAtualizar;
    private javax.swing.JButton ButtonDeletar;
    private javax.swing.JButton ButtonPesquisar;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JComboBox<String> ComboBoxCargo;
    private javax.swing.JFormattedTextField FormattedTextFieldTelefone;
    private javax.swing.JLabel LabelCargo;
    private javax.swing.JLabel LabelCpf;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelRG;
    private javax.swing.JLabel LabelSalario;
    private javax.swing.JLabel LabelTelefone;
    private javax.swing.JFormattedTextField TextFieldCPF;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JTextField TextFieldRG;
    private javax.swing.JTextField TextFieldSalario;
    private javax.swing.JLabel jLabel1;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
}
